messages:
  endGame: '宝探しゲームを終了しました。'
  ineligibleCommand: 'このコマンドは宝探しゲーム実行中のみ使用できます。'

game:
  initGameTime: 60


# 宝探しゲーム対象マテリアルの日本語表記一覧です。
# 対象マテリアルを【追加】した場合は、この一覧にもマテリアル名と日本語表記を追加してください。
# 対象マテリアルを【削除】した場合は、スコア一覧等でnullになるのを避けるため、既存のデータは削除しないでください。
material:
  DIRT: '土'
  SAND: '砂'
  OAK_LOG: 'オークの原木'
  DARK_OAK_LOG: 'ダークオークの原木'
  PUMPKIN: 'カボチャ'
  DANDELION: 'タンポポ'
  WHITE_WOOL: '白色の羊毛'
  BEEF: '生の牛肉'
  PORKCHOP: '生の豚肉'
  BONE: '骨'
  INK_SAC: 'イカスミ'
  LILY_OF_THE_VALLEY: 'スズラン'
  LAPIS_LAZULI: 'ラピスラズリ'
  RAW_GOLD: '金の原石'
  EMERALD: 'エメラルド'
  DIAMOND: 'ダイヤモンド'
  ENDER_PEARL: 'エンダーパール'
  ANCIENT_DEBRIS: '古代の残骸'
  WITHER_ROSE: 'ウィザーローズ'

