messages:
  endGame: '宝探しゲームを終了しました。'
  ineligibleCommand: 'このコマンドは宝探しゲーム実行中のみ使用できます。'

game:
  initGameTime: 60


# 宝探しゲーム対象マテリアルの日本語表記一覧です。
# 対象マテリアルを【追加】した場合は、この一覧にもマテリアル名と日本語表記を追加してください。
# 対象マテリアルを【削除】した場合は、スコア一覧等でnullになるのを避けるため、既存のデータは削除しないでください。
material:
  DIRT: '土'
  SAND: '砂'
  OAK_LOG: 'オークの原木'
  DARK_OAK_LOG: 'ダークオークの原木'
  DIAMOND: 'ダイヤモンド'